name: 'Use Checkout'
description: 'Prints a file, and then writes to it'
inputs:
  what-to-write:
    description: 'What we want to append to a file'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        echo Current working directory is:
        pwd
      shell: bash
    - run: cat ./docs/placeholder
      shell: bash
    - run: echo "${{ inputs.what-to-write }}" >> ./docs/placeholder
      shell: bash          

