name: learn-about-input-types
on:
  workflow_dispatch:
    inputs:
      check-manual:
        description: 'Check the manual'
        type: boolean
        default: 'false' # unlike with workflow_call, the online parser doesn't complain about using a string here

jobs:
  call-reusable-workflow-boolean:
    uses: ./.github/workflows/reusable.yaml
    with:
      check-manual: ${{ github.event.inputs.check-manual == 'true' }}

  call-reusable-workflow-string:
    uses: ./.github/workflows/reusable.yaml
    with:
      check-manual-string: ${{ github.event.inputs.check-manual }}

  call-reusable-workflow-inputs-context:
    uses: ./.github/workflows/reusable.yaml
    with:
      check-manual: ${{ inputs.check-manual }}

  # call-reusable-workflow-erroneous:
  #   uses: ./.github/workflows/reusable.yaml
  #   with:
  #     check-manual: ${{ github.event.inputs.check-manual }} # Won't work: github.event.inputs.check-manual, unlike inputs.check-manual, is a string; a boolean is required.

  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'github.event.inputs: ${{ toJSON(github.event.inputs) }}'
          echo 'inputs: ${{ toJSON(inputs) }}'