name: learn-about-input-types
on:
  workflow_dispatch:
    inputs:
      check-manual:
        description: 'Check the manual'
        type: boolean
        default: 'true' # unlike with workflow_call, the online parse doesn't complain about using a string here

jobs:
  call-reusable-workflow-boolean:
    uses: ./.github/workflows/reusable.yaml
    with:
      check-manual: ${{ github.event.inputs.check-manual == 'true' }}

  call-reusable-workflow-string:
    uses: ./.github/workflows/reusable.yaml
    with:
      check-manual-string: ${{ github.event.inputs.check-manual }}
