name: learn-github-actions
on:
  push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo '${{ toJSON(github.event) }}'
          echo "DONE"

