name: learn-github-actions
on:
  push:
    tags:
      - refs/tags/v*
jobs:
  test-out-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "GITHUB_REF = $GITHUB_REF"
          echo "GITHUB_REF_NAME = $GITHUB_REF_NAME"

