on:
  workflow_dispatch

jobs:
  example_matrix_original:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    steps:
      - run: |
          echo "matrix: ${{ toJSON(matrix) }}"

  example_matrix_reordered:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: pink
            animal: cat
          - color: green
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    steps:
      - run: |
          echo "matrix: ${{ toJSON(matrix) }}"

