on:
  workflow_call:
    inputs:
      check-manual:
        type: boolean
        default: 'false'
      check-manual-string:
        type: string
        default: 'false'

name: called-workflow

jobs:
  Echo-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: check-value-boolean
        run: |
          echo "Value of check-manual: ${{ inputs.check-manual }}"
          echo Is check-manual equal to true?: ${{ inputs.check-manual == true }}
          echo "Is check-manual equal to 'true'?: ${{ inputs.check-manual == 'true' }}"
          echo Is check-manual equal to false?: ${{ inputs.check-manual == false }}
          echo "Is check-manual equal to 'false'?: ${{ inputs.check-manual == 'false' }}"
      - name: check-value-string
        run: |
          echo Value of check-manual-string: ${{ inputs.check-manual-string }}
          echo Is check-manual-string equal to true?: ${{ inputs.check-manual-string == true }}
          echo "Is check-manual-string equal to 'true'?: ${{ inputs.check-manual-string == 'true' }}"
          echo Is check-manual-string equal to false?: ${{ inputs.check-manual-string == false }}
          echo "Is check-manual-string equal to 'false'?: ${{ inputs.check-manual-string == 'false' }}"
