on:
  workflow_call:
    inputs:
      check-manual:
        type: boolean
      check-manual-string:
        type: string

name: called-workflow

jobs:
  Echo-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: check-value-boolean
        run: |
          echo check-manual ${{ inputs.check-manual }}
          echo check-manual ${{ inputs.check-manual == true }}
          echo check-manual ${{ inputs.check-manual == 'true' }}
      - name: check-value-string
        run: |
          echo check-manual-string ${{ inputs.check-manual-string }}
          echo check-manual-string ${{ inputs.check-manual-string == true }}
          echo check-manual-string ${{ inputs.check-manual-string == 'true' }}
