on:
  workflow_call:
    inputs:
      check-manual:
        type: boolean

        # The online parser will complain "type is set to boolean ,
        # but default is of type string", but it will in fact work
        # just fine when run.  There is, of course, no reason not to
        # just use "false" (unquoted), without the expression
        # template.
        default: ${{ true }}

      check-manual-string:
        type: string
        default: 'true'
      string-using-format-function:
        type: string
        default: ${{ format('The event is {0}!', github.event_name) }}

name: called-workflow

jobs:
  Echo-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: check-value-boolean
        run: |
          echo "Value of check-manual: ${{ inputs.check-manual }}"
          echo Is check-manual equal to true?: ${{ inputs.check-manual == true }}
          echo "Is check-manual equal to 'true'?: ${{ inputs.check-manual == 'true' }}"
          echo Is check-manual equal to false?: ${{ inputs.check-manual == false }}
          echo "Is check-manual equal to 'false'?: ${{ inputs.check-manual == 'false' }}"
      - name: check-value-string
        run: |
          echo Value of check-manual-string: ${{ inputs.check-manual-string }}
          echo Is check-manual-string equal to true?: ${{ inputs.check-manual-string == true }}
          echo "Is check-manual-string equal to 'true'?: ${{ inputs.check-manual-string == 'true' }}"
          echo Is check-manual-string equal to false?: ${{ inputs.check-manual-string == false }}
          echo "Is check-manual-string equal to 'false'?: ${{ inputs.check-manual-string == 'false' }}"
          echo "string-using-format-function = ${{ inputs.string-using-format-function }}"

       # Compare inputs
      - name: Compare event inputs with workflow_call inputs
        run: |
          echo "inputs: ${{ fromJSON(github.event.inputs) }}"
          echo "inputs: ${{ fromJSON(inputs) }}"
