name: Test Casts
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  test_bash_echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ contains('-2.99e-2', 'e') }}"
          echo "${{ contains('-2.99e-2', e) }}"
          echo "${{ contains(-2.99e-2, 'e') }}"
          echo "${{ contains(-2.99e-2, e) }}"

          echo "${{ contains('-2.99e-2', '299') }}"
          echo "${{ contains('-2.99e-2', 299) }}"
          echo "${{ contains(-2.99e-2, '299') }}"
          echo "${{ contains(-2.99e-2, 299) }}"
