name: Test Casts
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  test_bash_echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ contains('-2.99e-2', 'e') }}"
          echo "${{ contains(-2.99e-2, 'e') }}"

          echo "${{ contains('-2.99e-2', '299') }}"
          echo "${{ contains('-2.99e-2', 299) }}"

          echo "${{ startsWith(-2.99e-2, '-0.0299') }}"
          echo "${{ endsWith(-2.99e-2, '.0299') }}"



          echo "${{ contains(-2.99e-2, '-0.0299') }}"
          echo "${{ contains('-0.0299', -2.99e-2) }}"


          # Are large numbers treated differently?
          echo "${{ contains(1e20, '10000000') }}"
          echo "${{ contains(1e20, 'e') }}"
          echo "${{ contains(1e20, 'e20') }}"
          echo "${{ endsWith(1e20, 'e20') }}"
          echo "${{ startsWith(1e20, '1') }}"
          echo "${{ startsWith(1e20, '1e') }}"
          echo "${{ startsWith(1e20, '1e+') }}"
          echo "${{ startsWith(1e20, '1e+2') }}"
          echo "${{ startsWith(1e20, '1e+20') }}"

          echo "${{ contains(1e20, '1e+20') }}"
          echo "${{ contains('1e+20', 1e20) }}"


