name: Test Casts
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  test_bash_echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ contains('-2.99e-2', 'e') }}"
          echo "${{ contains(-2.99e-2, 'e') }}"

          echo "${{ contains('-2.99e-2', '299') }}"
          echo "${{ contains('-2.99e-2', 299) }}"

          echo "${{ startsWith(-2.99e-2, '-0.0299') }}"
          echo "${{ endsWith(-2.99e-2, '.0299') }}"



          echo "${{ contains(-2.99e-2, '-0.0299') }}"
          echo "${{ contains('-0.0299', -2.99e-2) }}"
