name: Test More Casts
on:
  workflow_dispatch:

jobs:
  test_bash_echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ contains('false', 'e') }}" # true (as expected; both are strings)
          echo "${{ contains('null', 'u') }}"  # (ditto)

          # This shows false is stringified to 'false':
          echo "${{ contains(false, 'false') }}"
          echo "${{ contains('false', false) }}"

          # But null is not stringified to 'null':
          echo "${{ contains(null, 'u') }}" # false!

          # Rather, it is stringified to the empty string:
          echo "${{ contains('', null) }}"
          echo "${{ contains('any string', null) }}"
