name: Test status check functions

on:
  push:

  workflow_dispatch:

jobs:
  install:
    name: Checks

    runs-on: ubuntu-latest

    steps:

      - name: JobA
        id: seedBuild
        run: |
              echo "failing on purpose"
              exit 1
        continue-on-error: true

      - name: Debug Job Failure
        run: |
              echo "******** Job Logs from ********"
        if: steps.seedBuild.outcome == 'failure'

      - name: Will this run
        run: |
          echo This ran
