name: Test status check functions

on:
  push:

  workflow_dispatch:

jobs:
  install:
    name: Checks

    runs-on: ubuntu-latest

    steps:

      - name: JobA
        id: seedBuild
        run: |
              echo "failing on purpose"
              exit 1
        continue-on-error: true

      - name: JobB
        id: allJobs
        run: |
              echo "::set-output name=exit_code::$(echo -n "$?")"

      - name: Debug Job Failure
        run: |
              echo "******** Job Logs from ********"
              echo ${{ steps.allJobs.outputs.exit_code }}
        if: always() && (steps.seedBuild.outcome == 'failure' || steps.allJobs.outcome == 'failure')

      - name: Will this run
        run: |
          echo This ran
