name: learn-more-about-input-types
on:
  workflow_dispatch:
    inputs:
      bool_bool_1:
        description: 'Boolean of type boolean (default: true)'
        type: boolean
        default: true
      bool_bool_2:
        description: 'Boolean of type boolean (default: false)'
        type: boolean
        default: false
      bool_bool_3:
        description: 'Boolean of type boolean (default: expression template containing ''true'')'
        type: boolean
        default: ${{ 'true' }}
      bool_bool_4:
        description: 'Boolean of type boolean (default: expression template containing ''false'')'
        type: boolean
        default: ${{ 'false' }}
      bool_str_1:
        description: 'Boolean of type string (default: true)'
        type: string
        default: true
      bool_str_2:
        description: 'Boolean of type string (default: false)'
        type: string
        default: false
      bool_str_3:
        description: 'Boolean of type string (default: expression template containing ''true'')'
        type: string
        default: 'true'
      bool_str_4:
        description: 'Boolean of type string (default: expression template containing ''false'')'
        type: string
        default: 'false'
jobs:
  print_info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "bool_bool_1: ${{ github.event.inputs.bool_bool_1 }}"
          echo "bool_bool_2: ${{ github.event.inputs.bool_bool_2 }}"
          echo "bool_bool_3: ${{ github.event.inputs.bool_bool_3 }}"
          echo "bool_bool_4: ${{ github.event.inputs.bool_bool_4 }}"
          echo "bool_str_1: ${{ github.event.inputs.bool_str_1 }}"
          echo "bool_str_2: ${{ github.event.inputs.bool_str_2 }}"
          echo "bool_str_3: ${{ github.event.inputs.bool_str_3 }}"
          echo "bool_str_4: ${{ github.event.inputs.bool_str_4 }}"

          echo "bool_bool_1 == true: ${{ github.event.inputs.bool_bool_1 == true }}"
          echo "bool_bool_1 == 'true': ${{ github.event.inputs.bool_bool_1 == 'true' }}"
          echo "bool_bool_2 == true: ${{ github.event.inputs.bool_bool_2 == true }}"
          echo "bool_bool_2 == 'true': ${{ github.event.inputs.bool_bool_2 == 'true' }}"
          echo "bool_bool_3 == true: ${{ github.event.inputs.bool_bool_3 == true }}"
          echo "bool_bool_3 == 'true': ${{ github.event.inputs.bool_bool_3 == 'true' }}"
          echo "bool_bool_4 == true: ${{ github.event.inputs.bool_bool_4 == true }}"
          echo "bool_bool_4 == 'true': ${{ github.event.inputs.bool_bool_4 == 'true' }}"
          echo "bool_str_1 == true: ${{ github.event.inputs.bool_str_1 == true }}"
          echo "bool_str_1 == 'true': ${{ github.event.inputs.bool_str_1 == 'true' }}"
          echo "bool_str_2 == true: ${{ github.event.inputs.bool_str_2 == true }}"
          echo "bool_str_2 == 'true': ${{ github.event.inputs.bool_str_2 == 'true' }}"
          echo "bool_str_3 == true: ${{ github.event.inputs.bool_str_3 == true }}"
          echo "bool_str_3 == 'true': ${{ github.event.inputs.bool_str_3 == 'true' }}"
          echo "bool_str_4 == true: ${{ github.event.inputs.bool_str_4 == true }}"
          echo "bool_str_4 == 'true': ${{ github.event.inputs.bool_str_4 == 'true' }}"
