name: learn-more-about-input-types
on:
  workflow_dispatch:
    inputs:
      bool_bool_1:
        description: 'Boolean of type boolean (default: true)'
        type: boolean
        default: true
      bool_bool_2:
        description: 'Boolean of type boolean (default: false)'
        type: boolean
        default: false
      bool_bool_3:
        description: 'Boolean of type boolean (default: expression template containing ''true'')'
        type: boolean
        default: ${{ 'true' }}
        # Using a real boolean value here (e.g. default: ${{ true }}) gives a template error:
        #     A template expression is not allowed in this context
      bool_bool_4:
        description: 'Boolean of type boolean (default: expression template containing ''false'')'
        type: boolean
        default: ${{ 'false' }}
      bool_str_1:
        description: 'Boolean of type string (default: true)'
        type: string
        default: true
      bool_str_2:
        description: 'Boolean of type string (default: false)'
        type: string
        default: false
      bool_str_3:
        description: 'Boolean of type string (default: expression template containing ''true'')'
        type: string
        default: 'true'
      bool_str_4:
        description: 'Boolean of type string (default: expression template containing ''false'')'
        type: string
        default: 'false'

env:
  true-string-1: true
  true-string-2: ${{ 'true' }}
  true-string-3: 'true'
  true-string-4: !!bool true
  true-string-5: ${{ true }}

jobs:
  print_info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Output env comparisons with boolean true:"
          echo "true-string-1 == true: ${{ env.true-string-1 == true }}"
          echo "true-string-1 == true: ${{ env.true-string-1 == true }}"
          echo "true-string-1 == true: ${{ env.true-string-1 == true }}"
          echo "true-string-1 == true: ${{ env.true-string-1 == true }}"
          echo "true-string-1 == true: ${{ env.true-string-1 == true }}"

          echo "Output env comparisons with string true:"
          echo "true-string-1 == 'true': ${{ env.true-string-1 == 'true' }}"
          echo "true-string-1 == 'true': ${{ env.true-string-1 == 'true' }}"
          echo "true-string-1 == 'true': ${{ env.true-string-1 == 'true' }}"
          echo "true-string-1 == 'true': ${{ env.true-string-1 == 'true' }}"
          echo "true-string-1 == 'true': ${{ env.true-string-1 == 'true' }}"

          echo "Output all input values:"
          echo "bool_bool_1: ${{ github.event.inputs.bool_bool_1 }}"
          echo "bool_bool_2: ${{ github.event.inputs.bool_bool_2 }}"
          echo "bool_bool_3: ${{ github.event.inputs.bool_bool_3 }}"
          echo "bool_bool_4: ${{ github.event.inputs.bool_bool_4 }}"
          echo "bool_str_1: ${{ github.event.inputs.bool_str_1 }}"
          echo "bool_str_2: ${{ github.event.inputs.bool_str_2 }}"
          echo "bool_str_3: ${{ github.event.inputs.bool_str_3 }}"
          echo "bool_str_4: ${{ github.event.inputs.bool_str_4 }}"

          echo "Output comparison with boolean true:"
          echo "bool_bool_1 == true: ${{ github.event.inputs.bool_bool_1 == true }}"
          echo "bool_bool_2 == true: ${{ github.event.inputs.bool_bool_2 == true }}"
          echo "bool_bool_3 == true: ${{ github.event.inputs.bool_bool_3 == true }}"
          echo "bool_bool_4 == true: ${{ github.event.inputs.bool_bool_4 == true }}"
          echo "bool_str_1 == true: ${{ github.event.inputs.bool_str_1 == true }}"
          echo "bool_str_2 == true: ${{ github.event.inputs.bool_str_2 == true }}"
          echo "bool_str_3 == true: ${{ github.event.inputs.bool_str_3 == true }}"
          echo "bool_str_4 == true: ${{ github.event.inputs.bool_str_4 == true }}"

          echo "Output comparison with string 'true':"
          echo "bool_bool_1 == 'true': ${{ github.event.inputs.bool_bool_1 == 'true' }}"
          echo "bool_bool_2 == 'true': ${{ github.event.inputs.bool_bool_2 == 'true' }}"
          echo "bool_bool_3 == 'true': ${{ github.event.inputs.bool_bool_3 == 'true' }}"
          echo "bool_bool_4 == 'true': ${{ github.event.inputs.bool_bool_4 == 'true' }}"
          echo "bool_str_1 == 'true': ${{ github.event.inputs.bool_str_1 == 'true' }}"
          echo "bool_str_2 == 'true': ${{ github.event.inputs.bool_str_2 == 'true' }}"
          echo "bool_str_3 == 'true': ${{ github.event.inputs.bool_str_3 == 'true' }}"
          echo "bool_str_4 == 'true': ${{ github.event.inputs.bool_str_4 == 'true' }}"

          echo "Output comparison with boolean false:"
          echo "bool_bool_1 == false: ${{ github.event.inputs.bool_bool_1 == false }}"
          echo "bool_bool_2 == false: ${{ github.event.inputs.bool_bool_2 == false }}"
          echo "bool_bool_3 == false: ${{ github.event.inputs.bool_bool_3 == false }}"
          echo "bool_bool_4 == false: ${{ github.event.inputs.bool_bool_4 == false }}"
          echo "bool_str_1 == false: ${{ github.event.inputs.bool_str_1 == false }}"
          echo "bool_str_2 == false: ${{ github.event.inputs.bool_str_2 == false }}"
          echo "bool_str_3 == false: ${{ github.event.inputs.bool_str_3 == false }}"
          echo "bool_str_4 == false: ${{ github.event.inputs.bool_str_4 == false }}"

          echo "Output comparison with string 'false':"
          echo "bool_bool_1 == 'false': ${{ github.event.inputs.bool_bool_1 == 'false' }}"
          echo "bool_bool_2 == 'false': ${{ github.event.inputs.bool_bool_2 == 'false' }}"
          echo "bool_bool_3 == 'false': ${{ github.event.inputs.bool_bool_3 == 'false' }}"
          echo "bool_bool_4 == 'false': ${{ github.event.inputs.bool_bool_4 == 'false' }}"
          echo "bool_str_1 == 'false': ${{ github.event.inputs.bool_str_1 == 'false' }}"
          echo "bool_str_2 == 'false': ${{ github.event.inputs.bool_str_2 == 'false' }}"
          echo "bool_str_3 == 'false': ${{ github.event.inputs.bool_str_3 == 'false' }}"
          echo "bool_str_4 == 'false': ${{ github.event.inputs.bool_str_4 == 'false' }}"

          echo "Output comparison with null:"
          echo "bool_bool_1 == null: ${{ github.event.inputs.bool_bool_1 == null }}"
          echo "bool_bool_2 == null: ${{ github.event.inputs.bool_bool_2 == null }}"
          echo "bool_bool_3 == null: ${{ github.event.inputs.bool_bool_3 == null }}"
          echo "bool_bool_4 == null: ${{ github.event.inputs.bool_bool_4 == null }}"
          echo "bool_str_1 == null: ${{ github.event.inputs.bool_str_1 == null }}"
          echo "bool_str_2 == null: ${{ github.event.inputs.bool_str_2 == null }}"
          echo "bool_str_3 == null: ${{ github.event.inputs.bool_str_3 == null }}"
          echo "bool_str_4 == null: ${{ github.event.inputs.bool_str_4 == null }}"

          echo "Output comparison with the empty string:"
          echo "bool_bool_1 == '': ${{ github.event.inputs.bool_bool_1 == '' }}"
          echo "bool_bool_2 == '': ${{ github.event.inputs.bool_bool_2 == '' }}"
          echo "bool_bool_3 == '': ${{ github.event.inputs.bool_bool_3 == '' }}"
          echo "bool_bool_4 == '': ${{ github.event.inputs.bool_bool_4 == '' }}"
          echo "bool_str_1 == '': ${{ github.event.inputs.bool_str_1 == '' }}"
          echo "bool_str_2 == '': ${{ github.event.inputs.bool_str_2 == '' }}"
          echo "bool_str_3 == '': ${{ github.event.inputs.bool_str_3 == '' }}"
          echo "bool_str_4 == '': ${{ github.event.inputs.bool_str_4 == '' }}"
